// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4XGR6IIb2AgGH2o8NPIBuvO3XVAftS8',
    appId: '1:266900175450:web:10eec9c82f79d5a507f663',
    messagingSenderId: '266900175450',
    projectId: 'gamexplore-2024',
    authDomain: 'gamexplore-2024.firebaseapp.com',
    storageBucket: 'gamexplore-2024.appspot.com',
    measurementId: 'G-3PZLHE77JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3zGrafPG0fhbgLV1YscYcoE4WdztaABY',
    appId: '1:266900175450:android:2d0e8c41e282ecd007f663',
    messagingSenderId: '266900175450',
    projectId: 'gamexplore-2024',
    storageBucket: 'gamexplore-2024.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz4XGR6IIb2AgGH2o8NPIBuvO3XVAftS8',
    appId: '1:266900175450:web:fabbc8f03312ed9907f663',
    messagingSenderId: '266900175450',
    projectId: 'gamexplore-2024',
    authDomain: 'gamexplore-2024.firebaseapp.com',
    storageBucket: 'gamexplore-2024.appspot.com',
    measurementId: 'G-QHBB5YXKJS',
  );
}
